refactor: Get maintainers from output module
equinor/data-marketplace-adapter-service pull request #62
Opened 2023-04-11 07:23 UTC by aronhoyer

Fetches responsibilities, its users and roles from Collibra's output module.

Added tests for the handler and I'd like input on especially those tests. Things to consider when reviewing these tests:
- Are the all the sad paths covered?
- Are they giving false positives?

Resolves [AB#106057](https://dev.azure.com/EquinorASA/d02c350d-092d-41bf-a812-f05d5d8ad1b0/_workitems/edit/106057)

2023-04-11 09:16 UTC, nilsml requested changes
A couple of things to have a look at. We can go through it together.

2023-04-12 10:53 UTC, nilsml commented on lib/adapters/maintainer_adapter.spec.ts
> +    expect(E.isRight(maintainerAdapter({ role: role!, user: user! }))).toBe(true)
Should be ok, but I'd add a linter exception then to avoid the warning. Warnings that we are ok with should not be shown.

2023-04-12 10:54 UTC, aronhoyer commented on lib/adapters/maintainer_adapter.spec.ts
> +    expect(E.isRight(maintainerAdapter({ role: role!, user: user! }))).toBe(true)
good point! i'll disable it for test files 👍

2023-04-12 11:56 UTC, nilsml approved these changes
LGTM

2023-04-12 11:56 UTC, nilsml commented on GetMaintainersTrigger/lib/getMaintainersHandler.ts
> +    TE.mapLeft(toNetError(500)),
Functional composition can be used to create a function that do validateID and then wrap in a NetError

2023-04-12 12:27 UTC, aronhoyer commented
still don't understand why we have four checks that don't run

2023-04-12 12:28 UTC, merged